### ISSUE TITLE
Invoke-Sqlcmd -InputFile ./script.sql -ServerInstance $ServerUri -dat

### ISSUE THREAD

**Issue by greglambert-ar** [Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK#527]
Hi,

When setting up a new/test instance of the Azure Marketplace SaaS Accelerator, I was able to successfully start the PS script in an Azure cloud shell session,

All was going well, until this line:

https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=mariner.2.0-x64
      ➡️ Execute SQL schema/data script
Invoke-Sqlcmd: /home/greg/Commercial-Marketplace-SaaS-Accelerator/deployment/Deploy.ps1:346
Line |
 346 |  Invoke-Sqlcmd -InputFile ./script.sql -ServerInstance $ServerUri -dat …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find file '/home/greg/Commercial-Marketplace-SaaS-Accelerator/deployment/script.sql'.

Had a quick look, could not find the script.sql file locally

Any help would be much appreciated.

References: 

https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/deployment/Deploy.ps1

**Comment by greglambert-ar** [comment]
Hi,

We resolve the issue.

I am not sure that you can ever get this script to run on Azure Cloudshell.

So, we used Visual Code with the following installed:
1) .NET 6
2) AZ Commands for PowerShell
3) SQL Server for Powershell (very imporant!)

Once these components were installed along with the latest version of PWSH, we got it all running.

Cheers,

g

**Comment by santhoshb-msft** [comment]
Hi @greglambert-ar 
Also please see out [latest ](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md)install instructions which includes installing dotn6.0. previously this was not needed as cloudshell came in built with it but now that its upgraded to dotnet 7 due to which the builds were not successful and sql file was never created. We added instructions to install dotnet 6 before proceeding with the installation. Your above approach works from local as well. Closing this as no pending item, please let us know if anything we can help with.

**Comment by greglambert-ar** [comment]
Hi - thanks for coming back to me on this.

Much appreciated.

cheers,

g
